# Schüler-Lehrer-Relation

## Fragestellung

Wie unterscheiden sich die Schüler-Lehrer-Relationen zwischen öffentlichen
und freien Oberschulen in Sachsen, und wie haben sie sich über die Zeit
entwickelt?

In [2]:
import pandas as pd

df_schueler_lehrer = pd.read_csv(
    "../data/cleaned/schulen_schueler_lehrer.csv",
    sep=";",
)

display(df_schueler_lehrer.head())
df_schueler_lehrer.info()

,schuljahr,schulen_anzahl,klassen_anzahl,schueler_gesamt,schueler_maennlich,schueler_weiblich,lehrpersonen_gesamt,lehrpersonen_maennlich,lehrpersonen_weiblich
0,1995/96,659,9471,220371,120332,100039,14634,4580,10054
1,1996/97,657,9322,222608,120119,102489,14171,4344,9827
2,1997/98,651,9210,221100,118628,102472,14347,4366,9981
3,1998/99,648,9170,218147,116560,101587,14271,4327,9944
4,1999/00,643,9033,214149,113999,100150,14015,4256,9759

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   schuljahr               31 non-null     str
 1   schulen_anzahl          31 non-null     int64
 2   klassen_anzahl          31 non-null     int64
 3   schueler_gesamt         31 non-null     int64
 4   schueler_maennlich      31 non-null     int64
 5   schueler_weiblich       31 non-null     int64
 6   lehrpersonen_gesamt     31 non-null     int64
 7   lehrpersonen_maennlich  31 non-null     int64
 8   lehrpersonen_weiblich   31 non-null     int64
dtypes: int64(8), str(1)
memory usage: 2.3 KB

Problem: Es fehlt hier "schulart".
-->Prüfen: Anfang und Ende und Zeitraum des Datensatzes

In [5]:
display(df_schueler_lehrer.head(3).T)
display(df_schueler_lehrer.tail(3).T)
print(df_schueler_lehrer["schuljahr"].iloc[0])
print(df_schueler_lehrer["schuljahr"].iloc[-1])

                              0        1        2
schuljahr               1995/96  1996/97  1997/98
schulen_anzahl              659      657      651
klassen_anzahl             9471     9322     9210
schueler_gesamt          220371   222608   221100
schueler_maennlich       120332   120119   118628
schueler_weiblich        100039   102489   102472
lehrpersonen_gesamt       14634    14171    14347
lehrpersonen_maennlich     4580     4344     4366
lehrpersonen_weiblich     10054     9827     9981

                             28       29       30
schuljahr               2023/24  2024/25  2025/26
schulen_anzahl              370      375      376
klassen_anzahl             5120     5224     5329
schueler_gesamt          122653   124719   127078
schueler_maennlich        64504    65540    66913
schueler_weiblich         58149    59179    60165
lehrpersonen_gesamt        9304     9219     9259
lehrpersonen_maennlich     3057     3082     3168
lehrpersonen_weiblich      6247     6137     6091

1995/96
2025/26